#file per l ambiente di sviluppo
# per la produzione useremo semplicemente il dockerFile

FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]